### ISSUE TITLE
json.dumps error on discover

### ISSUE THREAD

**Issue by pblankley** [singer-io/tap-klaviyo#19]
I created a fresh venv with python 3.6.8 and installed `tap-klaviyo` version 0.1.1

This was the traceback running 
```
$ tap-klaviyo -c my_config.json -d
```

```
Traceback (most recent call last):
  File "/blahblah/ktt/venv/bin/tap-klaviyo", line 11, in <module>
    load_entry_point('tap-klaviyo==0.1.1', 'console_scripts', 'tap-klaviyo')()
  File "/blahblah/ktt/venv/lib/python3.6/site-packages/tap_klaviyo/__init__.py", line 151, in main
    do_discover(args.config['api_key'])
  File "/blahblah/ktt/venv/lib/python3.6/site-packages/tap_klaviyo/__init__.py", line 144, in do_discover
    print(json.dumps(discover(api_key), sys.stdout, indent=2))
TypeError: dumps() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given
```

Is there something I'm doing wrong, or does `tap-klaviyo` not support python 3.6?

**Comment by pblankley** [comment]
For the record, when I go in and change 

```
print(json.dumps(discover(api_key), sys.stdout, indent=2))
```

to 

```
print(json.dumps(discover(api_key), indent=2))
```

discover works fine.

**Comment by lightstrike** [comment]
@pblankley I just hit this issue as well and your fix works for me as well!

Have you been able to get this tap to fetch any custom Klaviyo metrics?

**Comment by pblankley** [comment]
@lightstrike I haven't tried yet! How about you?
